### ISSUE TITLE
落后chinese_province_city_area_mapper的commit会合并么

### ISSUE THREAD

**Issue by shibing624** [shibing624/addressparser#5]

**Comment by shibing624** [comment]
https://github.com/DQinYuan/chinese_province_city_area_mapper 是原始repo，基于它clone的[addressparser](https://github.com/shibing624/addressparser)，有些功能和数据已经改变，可以看着一个独立的repo了，这边不会合并原repo的新功能了，如果大家觉得有借鉴的地方，可以自己动手迁移功能，反正2个repo都是开源的。

如果觉得有比较好的功能，需要我迁移或者优化的，可以罗列下。

**Comment by peterzhangnull** [comment]
🫡
